# Generated by Django 3.2.10 on 2023-08-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0002_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='id',
        ),
        migrations.AddField(
            model_name='registration',
            name='Address',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='Customer_Name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='Customer_id',
            field=models.AutoField(default=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='Proof_Id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='Proof_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Customer Registration'),
        ),
        migrations.AddField(
            model_name='registration',
            name='Proof_Type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Password',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Username',
            field=models.CharField(blank=True, max_length=600, null=True, unique=True),
        ),
    ]
