# Generated by Django 3.2.10 on 2023-08-23 04:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0024_food_and_beverages'),
        ('Hotel_frontend', '0003_auto_20230821_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Booking_ID', models.AutoField(default=10000, primary_key=True, serialize=False)),
                ('Booking_Date', models.DateField(default=datetime.datetime(2023, 8, 23, 10, 8, 55, 370010))),
                ('Check_in', models.DateField()),
                ('Check_out', models.DateField()),
                ('Cust_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel_frontend.registration')),
                ('Room_Num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel_admin.room')),
            ],
        ),
    ]
