# Generated by Django 3.2.10 on 2023-08-23 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 21, 9, 3, 699016)),
        ),
    ]
