# Generated by Django 3.2.10 on 2023-08-30 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0005_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Check_Out_Time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Out Time'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Check_in_Time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='In Time'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Total_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=datetime.datetime(2023, 8, 30, 11, 59, 13, 696404)),
        ),
    ]
