# Generated by Django 3.2.10 on 2023-08-30 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0006_auto_20230830_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=datetime.datetime(2023, 8, 30, 12, 42, 27, 360752)),
        ),
    ]
