# Generated by Django 3.2.10 on 2023-09-01 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0012_auto_20230901_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beverages_booking',
            name='Selected_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=datetime.datetime(2023, 9, 1, 11, 46, 59, 537712)),
        ),
    ]
