# Generated by Django 3.2.10 on 2023-09-05 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0018_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='Messages',
            field=models.CharField(blank=True, max_length=11000, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=datetime.datetime(2023, 9, 5, 14, 1, 14, 655781)),
        ),
    ]
