# Generated by Django 3.2.10 on 2023-09-05 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0019_auto_20230905_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='Address1',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='Country',
            field=models.CharField(blank=True, max_length=1550, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='State',
            field=models.CharField(blank=True, max_length=1550, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=datetime.datetime(2023, 9, 5, 19, 35, 27, 564422)),
        ),
    ]
