# Generated by Django 3.2.10 on 2023-09-08 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0020_auto_20230905_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=900, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=datetime.datetime(2023, 9, 8, 11, 40, 32, 95294)),
        ),
    ]
