# Generated by Django 3.2.10 on 2023-09-10 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0021_auto_20230908_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Email',
            field=models.EmailField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=datetime.datetime(2023, 9, 10, 13, 50, 50, 398655)),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Beverages_Booking',
        ),
    ]
