# Generated by Django 3.2.10 on 2023-09-10 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0022_auto_20230910_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardHolder_Name', models.CharField(blank=True, max_length=900, null=True)),
                ('Card_Num', models.CharField(blank=True, max_length=50, null=True)),
                ('Amount', models.CharField(blank=True, max_length=900, null=True)),
                ('Expiry_Date', models.DateField()),
                ('CVV', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=datetime.datetime(2023, 9, 10, 21, 0, 12, 142552)),
        ),
    ]
