# Generated by Django 3.2.10 on 2023-09-10 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0023_auto_20230910_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=datetime.datetime(2023, 9, 10, 21, 22, 33, 253597)),
        ),
        migrations.AlterField(
            model_name='paymentdb',
            name='Expiry_Date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
