# Generated by Django 3.2.10 on 2023-09-11 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0028_auto_20230911_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_pay',
            name='Customer_ID',
        ),
    ]
