# Generated by Django 3.2.10 on 2023-09-11 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0029_remove_customer_pay_customer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_Pay',
        ),
    ]
