# Generated by Django 3.2.10 on 2023-09-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0031_customer_pay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_Pay',
        ),
    ]
