# Generated by Django 3.2.10 on 2023-09-11 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0033_auto_20230911_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdb',
            name='Cust_ID',
        ),
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=datetime.datetime(2023, 9, 11, 9, 28, 16, 902791)),
        ),
    ]
