# Generated by Django 3.2.10 on 2023-09-11 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0036_alter_booking_booking_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDB',
        ),
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=datetime.datetime(2023, 9, 11, 9, 49, 32, 358291)),
        ),
    ]
