# Generated by Django 3.2.10 on 2023-09-11 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0042_auto_20230911_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdb',
            name='cust',
        ),
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=datetime.datetime(2023, 9, 11, 11, 10, 54, 163235)),
        ),
    ]
