# Generated by Django 3.2.10 on 2023-09-13 05:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0045_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdb',
            name='Customer_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hotel_frontend.registration'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=datetime.datetime(2023, 9, 13, 10, 52, 21, 495595)),
        ),
    ]
