# Generated by Django 3.2.10 on 2023-09-13 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0046_auto_20230913_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=datetime.datetime(2023, 9, 13, 10, 55, 17, 685450)),
        ),
    ]
