# Generated by Django 3.2.10 on 2023-09-14 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0051_alter_booking_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_pg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Messages', models.CharField(blank=True, max_length=6000, null=True)),
                ('Name_User', models.CharField(blank=True, max_length=90, null=True)),
                ('Email', models.EmailField(blank=True, max_length=90, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=datetime.datetime(2023, 9, 14, 22, 42, 4, 727759)),
        ),
    ]
