# Generated by Django 3.2.10 on 2023-09-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0052_auto_20230914_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(),
        ),
    ]
