# Generated by Django 3.2.10 on 2023-09-14 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_frontend', '0054_alter_booking_booking_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_pg',
            new_name='Contact_DB',
        ),
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=datetime.datetime(2023, 9, 14, 22, 43, 37, 851295)),
        ),
    ]
