# Generated by Django 3.2.10 on 2023-07-29 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0002_auto_20230729_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel_Rooms',
            new_name='Hotel',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Room_Category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Room_Description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Room_Image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Room_price',
            new_name='Price',
        ),
    ]
