# Generated by Django 3.2.10 on 2023-07-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0003_auto_20230729_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person_Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Designation', models.CharField(blank=True, max_length=500, null=True)),
                ('Personal_Statement', models.CharField(blank=True, max_length=500, null=True)),
                ('Person_Image', models.ImageField(blank=True, null=True, upload_to='Team Members')),
            ],
        ),
    ]
