# Generated by Django 3.2.10 on 2023-07-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0005_rename_price_hotel_price_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(blank=True, max_length=6000, null=True)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('Services', models.CharField(blank=True, max_length=6000, null=True)),
                ('Product', models.CharField(blank=True, max_length=6000, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Hotel Features')),
            ],
        ),
        migrations.RenameModel(
            old_name='Team',
            new_name='Hotel_staff',
        ),
    ]
