# Generated by Django 3.2.10 on 2023-07-31 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0006_auto_20230731_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='Services',
            new_name='Information',
        ),
    ]
