# Generated by Django 3.2.10 on 2023-07-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0007_rename_services_features_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amenities_name', models.CharField(blank=True, max_length=900, null=True)),
                ('AMenities_image', models.ImageField(blank=True, null=True, upload_to='Amenties')),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel_staff',
            name='Personal_Statement',
        ),
    ]
