# Generated by Django 3.2.10 on 2023-08-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0008_auto_20230731_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenities',
            old_name='AMenities_image',
            new_name='Amenities_image',
        ),
        migrations.AddField(
            model_name='amenities',
            name='Amenities_des',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
