# Generated by Django 3.2.10 on 2023-08-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0009_auto_20230801_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='Amenities_image1',
            field=models.ImageField(blank=True, null=True, upload_to='Amenties'),
        ),
        migrations.AddField(
            model_name='features',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='Hotel Features'),
        ),
        migrations.AddField(
            model_name='features',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='Hotel Features'),
        ),
    ]
