# Generated by Django 3.2.10 on 2023-08-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0010_auto_20230808_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='Room Images'),
        ),
    ]
