# Generated by Django 3.2.10 on 2023-08-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0012_auto_20230809_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Image1', models.ImageField(blank=True, null=True, upload_to='Rooms')),
                ('Room_Image2', models.ImageField(blank=True, null=True, upload_to='Rooms')),
                ('Room_Image3', models.ImageField(blank=True, null=True, upload_to='Rooms')),
                ('Room_Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Rooms_Description', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
