# Generated by Django 3.2.10 on 2023-08-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0013_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='Room_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
