# Generated by Django 3.2.10 on 2023-08-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0014_rooms_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='Room_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
