# Generated by Django 3.2.10 on 2023-08-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0016_remove_rooms_room_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='Product',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
    ]
