# Generated by Django 3.2.10 on 2023-08-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0017_rooms_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='Room_Price',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
