# Generated by Django 3.2.10 on 2023-08-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0018_alter_rooms_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='Room_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
