# Generated by Django 3.2.10 on 2023-08-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0019_alter_rooms_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='Amenities_image1',
        ),
    ]
