# Generated by Django 3.2.10 on 2023-08-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0020_remove_amenities_amenities_image1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Room_Num', models.AutoField(primary_key=True, serialize=False)),
                ('Room_Type', models.CharField(blank=True, max_length=500, null=True)),
                ('Booked_From', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('Booked_To', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('Time_In', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('Time_Out', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('Availaibility', models.BooleanField(default=True, verbose_name='active status')),
            ],
        ),
    ]
