# Generated by Django 3.2.10 on 2023-08-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0021_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advanced_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='Rooms')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='Rooms')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='Rooms')),
                ('Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Description', models.CharField(blank=True, max_length=600, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Product', models.CharField(blank=True, max_length=6000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
