# Generated by Django 3.2.10 on 2023-08-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0022_auto_20230818_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Availaibility',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Booked_From',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Booked_To',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Time_In',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Time_Out',
        ),
        migrations.AddField(
            model_name='room',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='Room_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Frontend Availability Table'),
        ),
    ]
