# Generated by Django 3.2.10 on 2023-09-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_admin', '0024_food_and_beverages'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
